const RULES: ReadonlyArray<{ category: string; keywords: readonly string[] }> = [
  {
    category: "mercado",
    keywords: ["mercado", "supermerc", "atacad", "hortifruti", "padaria", "acougue", "sacolao"],
  },
  {
    category: "alimentacao",
    keywords: [
      "restaurante",
      "ifood",
      "rappi",
      "lanch",
      "bar ",
      "cafe",
      "pizzar",
      "burguer",
      "hamburg",
      "food",
      "doceria",
      "sorvete",
    ],
  },
  {
    category: "transporte",
    keywords: [
      "uber",
      "99app",
      "99 ",
      "99pop",
      "cabify",
      "posto",
      "combustiv",
      "ipiranga",
      "shell",
      "metro",
      "onibus",
      "bilhete unico",
      "estacion",
      "pedagio",
      "sem parar",
      "conectcar",
    ],
  },
  {
    category: "moradia",
    keywords: [
      "aluguel",
      "condominio",
      "imobiliaria",
      "luz",
      "energia",
      "enel",
      "cemig",
      "cpfl",
      "light",
      "agua",
      "sanea",
      "sabesp",
      "gas ",
      "comgas",
      "internet",
      "vivo",
      "claro",
      "tim ",
      "net ",
      "oi fibra",
    ],
  },
  {
    category: "saude",
    keywords: [
      "farmacia",
      "drogaria",
      "droga ",
      "hospital",
      "clinica",
      "medic",
      "laborator",
      "saude",
      "odonto",
      "dentista",
      "psico",
      "academia",
      "smartfit",
    ],
  },
  {
    category: "compras",
    keywords: [
      "loja",
      "magaz",
      "amazon",
      "mercadolivre",
      "mercado livre",
      "shopee",
      "aliexpress",
      "americanas",
      "renner",
      "riachuelo",
      "c&a",
      "zara",
      "centauro",
      "casas bahia",
    ],
  },
  {
    category: "lazer",
    keywords: [
      "netflix",
      "spotify",
      "cinema",
      "prime video",
      "disney",
      "hbo",
      "max ",
      "globoplay",
      "steam",
      "playstation",
      "xbox",
      "game",
      "viagem",
      "hotel",
      "airbnb",
      "decolar",
      "latam",
      "gol ",
      "azul ",
    ],
  },
  {
    category: "educacao",
    keywords: ["escola", "faculdade", "universidade", "curso", "udemy", "alura", "livraria", "ensino"],
  },
  {
    category: "assinaturas",
    keywords: ["assinatura", "mensalidade", "anuidade"],
  },
  {
    category: "contas",
    keywords: ["tarifa", "taxa ", "seguro", "cartorio", "advog", "contabil"],
  },
];

export function classifyExpense(description: string): string {
  const memo = description.toLowerCase();
  for (const rule of RULES) {
    if (rule.keywords.some((kw) => memo.includes(kw))) return rule.category;
  }
  return "outros";
}
